### ISSUE TITLE
[Style] Mission View UI 개선

### ISSUE THREAD

**Issue by bokoo14** [DeveloperAcademy-POSTECH/MC3-Team8-OceanView#10]
## 🛠 Issue

피그마의 수정된 작업 내약을 토대로 Mission View의 모든 UI를 수정합니다.

## 📝 To-do

- [x] 미션 게시판 헤더 수정
- [x] 미션 게시판 게시글 박스 및 설명 UI 수정
- [x] 미션 게시판 인증사진 업로드 버튼(+버튼) 생성 및 위치 조정
- [x] 인증 사진 업로드 뷰 미션 박스 수정
- [x] 인증 사진 업로드 뷰 사진 업로드 박스 수정
- [x] 미션 사진 업로드 뷰 공유 버튼 수정
