### ISSUE TITLE
[Feat]  HomeView

### ISSUE THREAD

**Issue by bokoo14** [DeveloperAcademy-POSTECH/MC3-Team8-OceanView#15]
## 🛠 Issue

<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team8-OceanView/assets/97583162/5511c82e-c899-48ef-8b79-c87b152467f2" width ="800">
탭바의 첫번째 뷰인 HomeView입니다

크게 2가지의 Case로 나눌 수 있습니다.
Case1) 그룹이 매칭되지 않은 상태
Case1-1) 하단의 "새로운 우연 만나기"버튼을 누르지 않은 상태
Case1-2) 하단의 "새로운 우연 만나기" 버튼을 누른 후, 매칭이 진행 중
Case1-3) 하단의 "새로운 우연 만나기" 버튼을 누른 후, 매칭이 완료되어 채팅방으로 이동 가능

Case2) 그룹이 매칭된 상태

## 📝 To-do

- [x] 그룹이 매칭되지 않았을때 뷰 
- [x] 그룹이 매칭된 후 뷰
- [x] 그룹이 매칭된 후 "채팅방 이동" 뷰가 뜰때
- [x] 그룹이 매칭된 상태의 홈뷰
