### ISSUE TITLE
[Feat] 채팅방 리스트 생성

### ISSUE THREAD

**Issue by bokoo14** [DeveloperAcademy-POSTECH/MC3-Team8-OceanView#2]
## 🛠 Issue

- TabView의 두번째인 채팅방 기능 구현

## 📝 To-do

- [x] 채팅방 리스트 구현
- [x] 뷰 빌더를 사용하여 채팅방 리스트의 각 컴포넌트 재활용되도록 만들기
- [x] 채팅방 상단 채팅방 RoundedRectangle 구현
