### ISSUE TITLE
[Feat] 인증 사진 업로드

### ISSUE THREAD

**Issue by bokoo14** [DeveloperAcademy-POSTECH/MC3-Team8-OceanView#7]
## 🛠 Issue

tabView의 3번째 뷰인 "미션 인증 게시판"에서 +버튼을 누르면 "인증 사진 업로드" 뷰로 이동합니다
상단에 "미션 인증 게시판"을 Rounded Rectangle로 구현하고, 우측 상단에 +모양의 NavigationLink로 인증 사진 업로드 뷰로 이동하게 합니다.

## 📝 To-do

- [x] 사진 선택 버튼을 누르면 사용자의 디바이스 내의 앨범에서 사진을 선택할 수 있도록 합니다
- [x] 사진을 선택하고, 업로드 버튼을 누르면 업로드 alert창을 띄워줍니다. 
- [x] 업로드 alert 창에서 업로드를 누르면 해당 사진이 사용자의 디바이스에 저장됩니다

**Comment by bokoo14** [comment]
Firebase 및 안증 사진 업로드 기능 구현완료
