### ISSUE TITLE
[Style] ChatView의 UI 개선

### ISSUE THREAD

**Issue by bokoo14** [DeveloperAcademy-POSTECH/MC3-Team8-OceanView#8]
## 🛠 Issue

ChatView의 UI를 개선합니다
피그마의 작업 내용을 토대로 디자인을 수정합니다

## 📝 To-do

- [x] 채팅방 리스트의 상단 헤더 부분 수정
- [x] 채팅방 리스트의 Box스타일 수정
- [x] 채팅방 내의 헤더 부분 수정
- [x] 채팅방 내의 하단 전송 버튼 수정
- [x] 채팅방의 말풍선 Box 수정
